// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmqkfpoblocahvtyohpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtcWtmcG9ibG9jYWh2dHlvaHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTU3OTQsImV4cCI6MjA2MjEzMTc5NH0.OU7TrZm2nyL14kIhBxmT9N-Fh2i9McSa5pFBxLgUtB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);