// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fedpxnllrjxomtwzzbnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZHB4bmxscmp4b210d3p6Ym5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDEzMjcsImV4cCI6MjA2MjE3NzMyN30.lJ9YbbCtWSwJDBuqaiZ3LMIF9srJiGdxRiACS4ojRdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);